name: Build, Package, and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake ninja
      - name: Configure
        run: cmake -B build -S . -G Ninja -DBUILD_THREADPOOL_TESTS=ON
      - name: Build
        run: cmake --build build --config Release
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
      - name: Package
        run: cd build && cpack -G TGZ
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Lumadi-ThreadPool-${{ runner.os }}
          path: build/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: artifacts/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    if: failure()
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete tag if tests failed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "Deleting tag $TAG_NAME"
          gh api --method DELETE /repos/${{ github.repository }}/git/refs/tags/$TAG_NAME
